name: Test and Deploy NestJS Docker Container

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build test Docker image
        shell: powershell
        run: |
          docker pull plex-history-app:test || true
          docker build --cache-from plex-history-app:test -t plex-history-app:test .

      - name: Run unit tests in Docker
        shell: powershell
        run: |
          New-Item -Path ./test-results -ItemType Directory -Force
          docker run --rm -v ${PWD}/test-results:/app/test-results plex-history-app:test sh -c "npm run test && cp -r coverage test-results/"

      - name: Archive test results
        if: always()
        shell: powershell
        run: |
          Compress-Archive -Path ./test-results -DestinationPath ./test-results.zip
          Write-Host "Test results archived"

  deploy:
    needs: test
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        shell: powershell
        run: |
          # Reuse layers from test image if possible
          docker build --cache-from plex-history-app:test -t plex-history-app:latest .

      - name: Create environment file
        shell: powershell
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
        run: |
          @"
          DB_HOST=${env:DB_HOST}
          NODE_ENV=production
          PORT=3000
          "@ | Out-File -FilePath .env -Encoding utf8

      - name: Run database migrations on the host
        shell: powershell
        run: |
          docker run --rm `
            --env-file .env `
            plex-history-app:latest `
            npm run migration:run

      - name: Deploy application container
        shell: powershell
        run: |
          docker stop plex-history-app; if (-not $?) { Write-Host "Container wasn't running, continuing..." }
          docker rm plex-history-app; if (-not $?) { Write-Host "Container didn't exist, continuing..." }

          docker run -d `
            --name plex-history-app `
            -p 3000:3000 `
            --env-file .env `
            --add-host=host.docker.internal:host-gateway `
            --restart unless-stopped `
            plex-history-app:latest `
            npm run start:prod

          docker ps -a

          docker image prune -f
          Remove-Item .env
