name: Deploy NestJS Docker Container

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and deploy Docker container
        run: |
          docker stop plex-history-app || true
          docker rm plex-history-app || true

          docker build -t plex-history-app:latest .

          docker run -d \
            --name plex-history-app \
            -p 3000:3000 \
            --restart unless-stopped \
            plex-history-app:latest

          docker image prune -f
