name: Test and Deploy NestJS Docker Container

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build test Docker image
        shell: powershell
        run: |
          docker pull plex-history-app:test -ErrorAction SilentlyContinue
          docker build -t plex-history-app:test .

      - name: Run unit tests in Docker
        shell: powershell
        run: |
          docker run --rm plex-history-app:test npm run test

          if ($LASTEXITCODE -ne 0) {
            Write-Error "Tests failed with exit code $LASTEXITCODE"
            exit 1
          } else {
            Write-Host "All tests passed successfully!"
          }

  deploy:
    needs: test
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        shell: powershell
        run: |
          docker build -t plex-history-app:latest .

      - name: Create environment file
        shell: powershell
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          FILE_STORAGE_API_URL: ${{ secrets.FILE_STORAGE_API_URL }}
        run: |
          @"
          DB_HOST=${env:DB_HOST}
          NODE_ENV=production
          PORT=3000
          FILE_STORAGE_API_URL=${env:FILE_STORAGE_API_URL}
          "@ | Out-File -FilePath .env -Encoding utf8

      - name: Run database migrations on the host
        shell: powershell
        run: |
          docker run --rm `
            --env-file .env `
            plex-history-app:latest `
            npm run migration:run

      - name: Deploy application container
        shell: powershell
        run: |
          $containerExists = docker ps -a --filter "name=plex-history-app" --format "{{.Names}}"
          if ($containerExists) {
            Write-Host "Stopping existing container"
            docker stop plex-history-app
            docker rm plex-history-app
          } else {
            Write-Host "Container doesn't exist, continuing..."
          }

          docker run -d `
            --name plex-history-app `
            -p 3000:3000 `
            --env-file .env `
            --add-host=host.docker.internal:host-gateway `
            --restart unless-stopped `
            plex-history-app:latest `
            npm run start:prod

          docker ps -a

          docker image prune -f
          Remove-Item .env
