name: Deploy NestJS Docker Container

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and deploy Docker container
        shell: powershell
        run: |
          docker stop plex-history-app; if (-not $?) { Write-Host "Container wasn't running, continuing..." }
          docker rm plex-history-app; if (-not $?) { Write-Host "Container didn't exist, continuing..." }

          docker build -t plex-history-app:latest .

          docker run -d `
            --name plex-history-app `
            -p 3000:3000 `
            --restart unless-stopped `
            plex-history-app:latest

          docker image prune -f
