name: deploy

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build test Docker image
        shell: powershell
        run: |
          docker pull plex-history-app:test -ErrorAction SilentlyContinue
          docker build -t plex-history-app:test .

      - name: Run unit tests in Docker
        shell: powershell
        run: |
          docker run --rm plex-history-app:test npm run test

          if ($LASTEXITCODE -ne 0) {
            Write-Error "Tests failed with exit code $LASTEXITCODE"
            exit 1
          } else {
            Write-Host "All tests passed successfully!"
          }

  deploy:
    needs: test
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        shell: powershell
        run: |
          docker-compose build plex-history-app

      - name: Run database migrations
        shell: powershell
        env:
          DB_HOST: host.docker.internal
          NODE_ENV: production
        run: |
          docker-compose run --rm `
            -e DB_HOST=$env:DB_HOST `
            -e NODE_ENV=$env:NODE_ENV `
            plex-history-app `
            npm run migration:run

      - name: Deploy services
        shell: powershell
        env:
          DB_HOST: host.docker.internal
          FILE_STORAGE_API_URL: http://file-storage:3001
          FILE_STORAGE_TIMEOUT_MS: 15000
          FILE_STORAGE_MAX_RETRIES: 3
          NODE_ENV: production
          PORT: 3000
        run: |
          $containerExists = docker ps -a --filter "name=plex-history-app" --format "{{.Names}}"
          if ($containerExists) {
            Write-Host "Stopping existing container"
            docker-compose stop plex-history-app
            docker-compose rm -f plex-history-app
          } else {
            Write-Host "Container doesn't exist, continuing..."
          }

          docker-compose up -d plex-history-app

          docker-compose ps

      - name: Cleanup
        shell: powershell
        run: |
          docker image prune -f
